package checklist.data;

import checklist.model.Course;

import java.io.*;
import java.util.ArrayList;
import java.util.List;

/**
 * StudentRecordManager.java
 *
 * Handles saving and loading the student's personal grade record to/from disk.
 * The record file stores the full course list (curriculum + any extra courses
 * the student has added) in a pipe-delimited format that matches Course.toString().
 *
 * Save format per line:
 *   COURSE_NO|TITLE|UNITS|PREREQ|YEAR|TERM|GRADE|CREDITED|CREDITED_FROM|ACTUAL_NO|ACTUAL_TITLE
 *
 * Author  : Member 2
 * Section : CS 122 - [Section]
 * Date    : [Date]
 */
public class StudentRecordManager {

    private final String recordFilePath;

    // -------------------------------------------------------------------------
    // Constructor
    // -------------------------------------------------------------------------

    public StudentRecordManager(String recordFilePath) {
        this.recordFilePath = recordFilePath;
    }

    // -------------------------------------------------------------------------
    // Public methods
    // -------------------------------------------------------------------------

    /**
     * Saves the full course list to the record file, overwriting any previous data.
     *
     * @param courses the current list of all courses (curriculum + extras)
     * @throws IOException if the file cannot be written
     */
    public void save(List<Course> courses) throws IOException {
        // Ensure parent directories exist
        File file = new File(recordFilePath);
        if (file.getParentFile() != null) {
            file.getParentFile().mkdirs();
        }

        try (PrintWriter pw = new PrintWriter(new FileWriter(file))) {
            pw.println("# BSCS Checklist - Student Record");
            pw.println("# Auto-generated by ChecklistApp. Do not edit manually.");
            pw.println("# Format: COURSE_NO|TITLE|UNITS|PREREQ|YEAR|TERM|GRADE|CREDITED|CREDITED_FROM|ACTUAL_NO|ACTUAL_TITLE");
            pw.println("#");
            for (Course c : courses) {
                pw.println(c.toString());
            }
        }
    }

    /**
     * Loads the student's saved record from disk.
     * Returns an empty list if no record file exists yet (first run).
     *
     * @return list of courses restored from file
     * @throws IOException if the file exists but cannot be read
     */
    public List<Course> load() throws IOException {
        List<Course> courses = new ArrayList<>();
        File file = new File(recordFilePath);

        if (!file.exists()) {
            return courses; // no record yet — caller should load curriculum instead
        }

        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line;
            int lineNumber = 0;

            while ((line = br.readLine()) != null) {
                lineNumber++;
                line = line.trim();
                if (line.isEmpty() || line.startsWith("#")) continue;

                // Split into up to 11 parts
                String[] p = line.split("\\|", 11);
                if (p.length < 6) {
                    System.out.printf("[WARNING] Skipping malformed record line %d%n", lineNumber);
                    continue;
                }

                try {
                    String no     = p[0].trim();
                    String title  = p[1].trim();
                    double units  = Double.parseDouble(p[2].trim());
                    String prereq = p[3].trim();
                    int    year   = Integer.parseInt(p[4].trim());
                    String term   = p[5].trim();

                    Course c = new Course(no, title, units, prereq, year, term);

                    if (p.length > 6  && !p[6].trim().isEmpty())
                        c.setGrade(p[6].trim());
                    if (p.length > 7  && !p[7].trim().isEmpty())
                        c.setCredited(Boolean.parseBoolean(p[7].trim()));
                    if (p.length > 8  && !p[8].trim().isEmpty())
                        c.setCreditedFrom(p[8].trim());
                    if (p.length > 9  && !p[9].trim().isEmpty())
                        c.setActualCourseNo(p[9].trim());
                    if (p.length > 10 && !p[10].trim().isEmpty())
                        c.setActualTitle(p[10].trim());

                    courses.add(c);

                } catch (NumberFormatException e) {
                    System.out.printf("[WARNING] Skipping record line %d — bad number format%n",
                            lineNumber);
                }
            }
        }

        return courses;
    }

    /** Returns true if a saved record file already exists on disk. */
    public boolean recordExists() {
        return new File(recordFilePath).exists();
    }
}
